### Exercise 1 -- read and write files

 1. Read the file "file.vtk" and count the number of lines in the file (use readlines)
 2. Go back to the beginning of the file, cycle on the number of lines and read the file row by row; only print lines that do not start with a '#' (use readline, seek)
 3. Define a function to find the "POINTS" field, find the number of points (it is just after the points string, with no new line -- check the file if you are bot sure) and print the points on a file named points.txt. Do the same with the "POLYGONS" field
   -- to find the field, you can use the string method find(). Use the help() or ? to understand how find() works if you need it

In [1]:
# 1.
print("****  1  ****\n") 
# first of all, we open the file
f = open("file.vtk", "r") # you can also use try: ... except:... to check if file exists
# in particular we read its lines by putting them all inside a list,
# through the use of the readlines method 
flines = f.readlines()
# we assign the lenght of the list (aka the number of lines) to a new
# variable by using the builtin line len
nLines = len(flines)
print("file.vtk has "+str(nLines)+" lines")


# 2. 
print("\n****  2  ****\n") 
# we move now to the beginning of the file by using seek, whose input
# is the position with respect to the beginning of the file itself 
# and will therefore be set to 0
f.seek(0)
# we then have to cycle on the number of lines
for i in range(nLines):
# and, as before, read the file row by row by defining a variable that
# corresponds to the output of the readline method (which only reads
# one single line of the file - NB IT'S DIFFERENT from readlines!!!)
# and is therefore a string:
    line=f.readline()
# and only print lines which do not start with hashtags (#):
    if line[0] !=  "#":
        print(line, end="") #note: otherwise the newlines in the file are 
                            #taken but also print add a newline by default 
                            #(the default is end = "\n")

# 3.              
print("\n****  3  ****\n")               
# we can define a function that does what we want, whose arguments are:
# - the name of the file fname
# - a default set argument field (= "POINTS")
# - another default set argument outfile (= "points.txt")
def find_field_print_file(fname, field = "POINTS", outfile = "points.txt"):
    """This function finds the number of elements following a provided field pattern 
    and print them into a file."""
# we use the try ... except ... construct, that is quite useful 
# we then try to open the file with the given name
    try: 
        fl = open(fname, "r")  
# if the file doesn't exist, usually the interpreter would throw an
# error and stop the execution, but by using this construct we can
# just inform that the given name is wrong and then return from the 
# function (without stopping the execution of the code):
    except IOError: #IO error = input/output error
            print("File "+fname+" not found!")
            return
# we can then cycle indefinitely
    while True:
        line = fl.readline()
# looking, line by line, for the field that we passed as an argument
# by using the string method find, which returns the lowest index in
# the string where the input substring is found
# we keep checking until the index corresponding to the substring is -1
        if line.find(field) != -1: # remember find returns -1 if it does not find the string 
            break                  # you are looking for
# and, when we get there, we break from the cycle because it means
# we found the line where the desired field is:
# we can estract the info we need by first splitting the line based
# on the spacing (by using the string method split)
    npoints = line.split(" ")[1]
# and then turning the desired character from a string to the desired
# type of variable
    npoints = int(npoints)
# then we use the last argument of the function
    fo = open(outfile, "w")
# and cycle over the number that we just found
    for i in range(npoints):
# and each time wr write the same line working from (and each time
# we need to read it again)
        fo.write(fl.readline())
# finally, we close both of the files
    fo.close()
    fl.close()
    
    return npoints
    
# let's apply the function
n1 = find_field_print_file("file.vtk") #default is POINTS, points.txt
n2 = find_field_print_file("file.vtk", field = "POLYGONS", outfile = "polygons.txt")

print("n1 =",n1)
print("n2 =",n2)

****  1  ****

file.vtk has 44 lines

****  2  ****

Cube example
ASCII

DATASET POLYDATA
POINTS 8 float
0.0 0.0 0.0
1.0 0.0 0.0
1.0 1.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0
1.0 0.0 1.0
1.0 1.0 1.0
0.0 1.0 1.0
POLYGONS 6 30
4 0 1 2 3
4 4 5 6 7
4 0 1 5 4
4 2 3 7 6
4 0 4 7 3
4 1 2 6 5

POINT_DATA 8
SCALARS my_scalars float
LOOKUP_TABLE custom_table
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
LOOKUP_TABLE custom_table 8
0.0 0.0 0.0 1.0
1.0 0.0 0.0 1.0
0.0 1.0 0.0 1.0
1.0 1.0 0.0 1.0
0.0 0.0 1.0 1.0
1.0 0.0 1.0 1.0
0.0 1.0 1.0 1.0
1.0 1.0 1.0 1.0

****  3  ****

n1 = 8
n2 = 6


### Exercise 2 -- file manipulation
A (b/w) digital image can be saved as a matrix in which each entry represents a shade of grey. One of these formats is for instance the PGM (portable graymap)
Write a code that generates an image with inverted colors of the file "FACE.pgm" and saves in the file "NEGATIVE.pgm"

Note that the PGM file format is made so that the first line contains a string, the next contains two integers with the width x height of the image matrix (in fact, you don't need those, which can be pasted as they are in the negative file you are producing), and the third line contains the MAX_VAL, the max value allowed in the following matrix, that corresponds to black, while white is 0. The following lines contain the matrix. To produce a negative, you can simply do (MAX_VAL - matrix value) for each of the matrix entries.

Note: Each row in the file does NOT correspond to a pixel row in the image! This should not be relevant for your code anyways

In [2]:
# first of all, we open the we want to make the negative of:
input_im = open("FACE.pgm", "r")
# and the file that's going to store the negative:
output_im = open("NEGATIVE.pgm", "w")
# we import all the lines of the original as a list of strings:
all_lines = input_im.readlines()
# and we isolate the useful information (maximum value) that we
# know are already saved in the original file:
MAX_VAL = int(all_lines[2])
# to then copy the first three lines identically in the new file:
output_im.writelines(all_lines[:3])
# with list comprehension, we invert each value in each line:
inverted_lines = ["".join([str(int(MAX_VAL)-int(val))+" " for val in line.split()])+"\n" for line in all_lines[3:]] 
# note: split() takes all whitespaces as " ", tab, newline as
# default separators
# finally, we add the result to the output file
output_im.writelines(inverted_lines)
# and close the files that had been opened
input_im.close()
output_im.close()

### Exercise 3 -- files, directories, permissions

Write a code that prints your current directory.
Print the statistics of a file in the new directory. Change the file and its permissions. Print the statistics another time.
Then change directory and go in a different directory of your choice.
Go back to your original directory.

### Exercise 4

Your code should be able to enter a given directory and search for a given string in all files with a given extension. 

### Exercise 5 -- basic numpy

 a. Construct a numpy array from the list [1,2,3] and print it
 
 b. Cast the created numpy array into floats
 
 c. Create an array of int ranging from 0-10
 
 d. Create an array containing 7 evenly spaced numbers between 0 and 23
 
 e. Create an array containing 5 logarithmically spaced numbers between 0.01 and 100
 
 f. Create an array with shape (2,5,5,2) containing only the number 9.2
 
 g. Reshape the resulting array from shape (2,5,5,2) to only 2D (10x10)
 
 j. Starting from a=numpy.arange(10) and b=numpy.arange(5) create the array [0,1,2,3,4,4,3,2,1,0]
 

In [3]:
import numpy as np

# a. 
# we initialize the list
mylist = [1,2,3]
# and use the numpy array function
myarray = np.array(mylist)
print(myarray)

# b. 
# we can use the ndarray method:
myfloatarray = myarray.astype(float)
# or use the previously used function with one more specification:
myfloatarray = np.array(myarray,dtype=float)
print(myfloatarray)

# c.
# it's pretty straight forward since the required vector starts from 0
arr = np.arange(10,dtype = int)
print(arr)

# d.
# same, pretty easy
arr2 = np.linspace(0,23,7)
print(arr2)

# e.
# there's already a useful numpy built-in function
arr3 = np.logspace(-2, 2, 5)
# and it's pretty easy to recreate
arr3 = 10**np.linspace(-2, 2, 5)
print(arr3)

# f.
# we can exploit, yet again, a built in function and the intuitive
# operation properties of ndarrays
arr4 = np.ones((2,5,5,2))*9.2
print(arr4.shape, arr4[0][0][0][0])

# g. 
# it's intuitive
arr5 = arr4.reshape(10,10)
print(arr5)

#g 
# let's initialize the given arrays
a=np.arange(10) 
b=np.arange(5)
# we are going to work on the longer one, whose first half of the 
# digits are already right: we therefore need to work on the last 5
# by substituting them with the switched-around shorter vector
a[5:] = b[::-1]
print(a)

[1 2 3]
[1. 2. 3.]
[0 1 2 3 4 5 6 7 8 9]
[ 0.          3.83333333  7.66666667 11.5        15.33333333 19.16666667
 23.        ]
[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]
(2, 5, 5, 2) 9.2
[[9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]
 [9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2 9.2]]
[0 1 2 3 4 4 3 2 1 0]


### Exercise 6 -- basic numpy

 a.  Calculate the mean, std, var, max, min,  of an array with shape (15,15) containing floats drawn from a normal distribution with mean 21 and sigma 4.5 (use numpy.random.normal())
 
 b. Do the same but not on all elements, just on the 2nd dimension
 
 c. Transform the array so that it becomes 1d
 
 d. Use the flattened array to remove all values smaller 15 and larger 26. 
 
 e. Clip all values smaller 15 and larger 26 to NaN (hint:clip )
 
 f. Calculate the sum of the resulting array. It should not be NaN! (hint:nansum)
 
 g. Convert the NaN's to 0.0 (hint: nan_to_num)
 
 h. Save the  array into a file and then load it again

In [4]:
import numpy as np

# a.
# we use the numpy submodule random: in particular, its function
# normal and its methods, which allow for a quick statistical analysis
norm_array=np.random.normal(21.,4.5, size=(15,15))
print("mean     ="+str(norm_array.mean()))
print("st dev   ="+str(norm_array.std()))
print("variance ="+str(norm_array.var()))
print("max ="+str(norm_array.max()))
print("min ="+str(norm_array.min())+'\n')

# b.
# we use the same submodule, function and modules but we add one more
# specification
norm_array=np.random.normal(21.,4.5, size=(15,15))
print("mean     ="+str(norm_array.mean(axis=1)))
print("st dev   ="+str(norm_array.std(axis=1)))
print("variance ="+str(norm_array.var(axis=1)))
print("max ="+str(norm_array.max(axis=1)))
print("min ="+str(norm_array.min(axis=1))+'\n')

# c.
# instead of using reshape (as seen in previous examples), we can
# use the method flatten:
new_array = norm_array.flatten()
print(len(new_array))

# d.
# we use the clip method to set all elements below 15 and above 26
# to set them equal to the boundaries:
clip_array = new_array.clip(min=15,max=26)
# alternatively, we could have used boolen masks twice  (<= doesn't work)
# to later use two a boolean masks to turn them into NaN
clip_array[clip_array==15] = np.NaN
clip_array[clip_array==26] = np.NaN
#print(clip_array)

# f.
# there's a very specific funtion that doesn't take NaN into account
# when summing
print(str(np.nansum(clip_array))+' is different from '+str(sum(clip_array)))

# g.
# again, there's a very specific yet useful funcion called nan_to_num
# that sets all the NaN to a certain numbers:
other_array=np.nan_to_num(clip_array, nan=0.)
#print(other_array)

# h.
# we use the very simple numpy functions loadtxt and savetxt
np.savetxt('lastarray.dat',other_array)
loaded_array = np.loadtxt('lastarray.dat')

mean     =21.108707580802523
st dev   =4.507450153376048
variance =20.31710688516976
max =33.01085501285173
min =9.22364509204196

mean     =[21.97424056 20.8587337  20.14148911 21.78982165 22.0720932  20.01720477
 22.04559719 20.5047563  20.92357386 20.28568447 21.28392336 21.75569987
 19.83651708 19.49668348 20.51287578]
st dev   =[4.42846556 5.63305136 5.11484496 5.72806051 3.88263955 3.79416103
 5.29193161 5.14359498 3.85629872 4.88416457 2.82581606 3.78808323
 5.002523   4.65944094 4.78083328]
variance =[19.61130721 31.73126761 26.16163894 32.81067726 15.07488985 14.39565789
 28.00454019 26.45656934 14.87103979 23.85506356  7.9852364  14.34957453
 25.02523635 21.7103899  22.85636685]
max =[30.81061121 35.14732254 30.69479769 30.26910176 28.63974177 25.57790547
 32.26280334 29.02345966 28.93646049 27.06917131 25.96059301 27.4532695
 25.74878876 25.94075462 29.6178136 ]
min =[13.67443357 14.4958137  11.94386338  8.21574527 16.47730305 11.32377052
 14.91451812 10.55276188 15.3336932 

### Exercise 7 -- numpy arrays, slicing

Use array slicing to approximate the numeric derivative of $\sin(x)$ in the range $[0, 2\pi]$.

Compute the maximum distance between the numeric and analytic derivative and the average of this distance along the entire grid of data.

Explore how the result varies depending on the number of points in your sample.

In [5]:
# the numerical derivatives can be obtained from the division of
# the increase of the function by the corresponding interval dx:
dim=500
extremes=np.linspace(0.,2.*np.pi,dim)
dx=extremes[1:]-extremes[:-1]
y=np.sin(extremes)
dy=y[1:]-y[:-1]
numerical=dy/dx
# instead, the analytical form should be calculated by calculated
# in the midpoint of the intervals that we are considering
centres=(extremes[1:]+extremes[:-1])/2
analytical=np.cos(centres)
diff=numerical-analytical
print(diff.mean())
# we can see that the average value dicreases as we increase the number
# of iterations dim within the requested interval

-1.7303779762874864e-18


### Exercise 8a -- numpy dtypes

Create a new numpy data type (atom) that represents a 3D atom. The dtype should contain:
  * a string("S3")  to represent the atom symbol
  * an integer to represent the atomic weight
  * three floats to represent the cartesian coordinates $(x,y,z)$
  
Create an array with dtype = atom that represents the water molecule H2O:
    (O coordinate 0,0,0, H coordinate 0, 0, 1.89, H coordinate 1.861,0,-0.328)

In [6]:
import numpy as np
# let's create the custom data type data 
atom=np.dtype([('symbol',np.unicode_,16),('atomic_weight',int),
               ('x',np.float64), ('y',np.float64), ('z',np.float64)])
# and apply it to water:
water=np.array([('O',8,0.,0.,0.),('H',1,0.,0.,1.89),
                ('H',1,0.,0.,1.89)],dtype=atom)
print(water)
print(water.dtype)

[('O', 8, 0., 0., 0.  ) ('H', 1, 0., 0., 1.89) ('H', 1, 0., 0., 1.89)]
[('symbol', '<U16'), ('atomic_weight', '<i4'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')]


### Exercise 8b -- numpy dtypes

a. Use numpy to load the file "mol.xyz" in a numpy array with dtype=atom.  Print the content of the array.

b. Isolate the array containing atomic weights and compute the molecular weight 
$\sum_i (\rm atomic\ weight)_i$

c. Compute the contribution of each atom in the total molecular weight.

d. Build a new numpy array with containing the cartesian coordinates of the atoms, print the array shape and its mean for the x, y and z component.

e. Then compute the molecular centre of mass: $x_{\rm cm} = (\sum_i m_i x_i)/ \sum m_i; y_{\rm cm} = (\sum_i m_i y_i)/ \sum m_i; z_{\rm cm} = (\sum_i m_i z_i)/ \sum m_i$

f. Finally compute the inertia tensor of the molecule: 

![alt text](imagename.png "Title")

In [7]:
# a.
mol=np.loadtxt('mol.xyz',dtype=atom)
#print(mol+'\n')

# b. 
# let's isolate the atomic weight, which by definition is a property
# of atom type objects
atomic_weight=mol['atomic_weight']
mol_weight=atomic_weight.sum()
print('the molecular weight of mol.xyz is '+str(mol_weight)+'\n')

# c.
# the idea is to take all the names of the atoms and put them in a set
# so there's no repetition:
mol_elem=list(set(mol['symbol']))
print(mol_elem)
temp=0
# we then cycle over the atoms that we found 
for elem in mol_elem:
# in order to isolate just those atoms and sum their contributes 
# thanks to a boolean mask and to the sum method of strings
    temp=mol[mol['symbol']==elem]['atomic_weight'].sum()
    print(elem+' contribute is : '+str(temp)+' out of '+str(mol_weight)+' ( '+str(100.*temp/mol_weight)+' % ).')
print('\n')

# d. 
# let's create the array with the spacial coordinates:
coord=np.array([mol['x'],mol['y'],mol['z']])
# its shape can be easily obtained through the corresponding method:
print('the shape of the array is ',coord.shape)
# and same goes with the averages for each coordinate and the 
# method mean (along the required axis)
print('the x coordinate mean is '+str(coord.mean(axis=1)[0]))
print('the y coordinate mean is '+str(coord.mean(axis=1)[1]))
print('the z coordinate mean is '+str(coord.mean(axis=1)[2])+'\n')

# e. 
# the coordinates of the center of mass correspond to the weighted
# average of each set of coordinates: we therefore exploit the ufunc
# product and the sum method
x_cm=(atomic_weight*coord[0]).sum() / mol_weight
y_cm=(atomic_weight*coord[1]).sum() / mol_weight
z_cm=(atomic_weight*coord[2]).sum() / mol_weight
print('the x of the center of mass is '+str(x_cm))
print('the y of the center of mass is '+str(y_cm))
print('the z of the center of mass is '+str(z_cm)+'\n')

# f.
# the inertia tensor has to deal with an ever more complicated formula
# that would take much more to compute with a loop, but we thank god
# again for the existence of ufunc product between numpy arrays and
# of the sum method:
I_xx=(atomic_weight*(coord[1]**2+coord[2]**2)).sum()
I_yy=(atomic_weight*(coord[0]**2+coord[2]**2)).sum()
I_zz=(atomic_weight*(coord[0]**2+coord[1]**2)).sum()
I_xy=-(atomic_weight*coord[0]*coord[1]).sum()
I_xz=-(atomic_weight*coord[0]*coord[2]).sum()
I_yz=-(atomic_weight*coord[1]*coord[2]).sum()
mat_inertia=np.matrix([[I_xx, I_xy, I_xz],
                       [I_xy, I_yy, I_yz],
                       [I_xz, I_yz, I_zz]])
print('the inertial tensor of mol.xyz is : \n', mat_inertia)

the molecular weight of mol.xyz is 458

['N', 'O', 'H', 'C']
N contribute is : 28 out of 458 ( 6.11353711790393 % ).
O contribute is : 32 out of 458 ( 6.986899563318778 % ).
H contribute is : 26 out of 458 ( 5.676855895196507 % ).
C contribute is : 372 out of 458 ( 81.22270742358079 % ).


the shape of the array is  (3, 61)
the x coordinate mean is -6.1036393442622945
the y coordinate mean is 1.8038360655737706
the z coordinate mean is 7.491770491803278

the x of the center of mass is -6.031115720524016
the y of the center of mass is 1.8624978165938864
the z of the center of mass is 7.536048034934497

the inertial tensor of mol.xyz is : 
 [[ 47408.39735   10068.852991  35951.289303]
 [ 10068.852991  74181.085975 -12473.020517]
 [ 35951.289303 -12473.020517  34525.947869]]


### Exercise 9 -- numpy vectorization

Create two arrays, $x$ and $h(x)$, where x is an evenly spaced interval in the range $[-4,4]$, and:
\begin{equation}
h(x) = \frac{1}{\sqrt{2\pi}} e^{-\frac 1 2 x^2}
\end{equation}

Try to create the arrays in two ways: 
 * with the `numpy.zeros()` function combined with a `for` loop
 * with linspace and operating directly on the vector.
 
Check the results are the same in the two cases.
You can use the `%%time` command to time the execution in two different cells

In [9]:
%%time
import numpy as np
num=20
x=np.linspace(-4,4,num)
h=1/np.sqrt(2*np.pi)*np.exp(-0.5*x**2)
print(x,h)

# done in 23/03 lecture -> correction is around min 78

[-4.         -3.57894737 -3.15789474 -2.73684211 -2.31578947 -1.89473684
 -1.47368421 -1.05263158 -0.63157895 -0.21052632  0.21052632  0.63157895
  1.05263158  1.47368421  1.89473684  2.31578947  2.73684211  3.15789474
  3.57894737  4.        ] [1.33830226e-04 6.59934041e-04 2.72554160e-03 9.42781527e-03
 2.73133694e-02 6.62743467e-02 1.34685734e-01 2.29247023e-01
 3.26807320e-01 3.90198694e-01 3.90198694e-01 3.26807320e-01
 2.29247023e-01 1.34685734e-01 6.62743467e-02 2.73133694e-02
 9.42781527e-03 2.72554160e-03 6.59934041e-04 1.33830226e-04]
Wall time: 2 ms


### Exercise 10 -- vectorization

Implement two different versions of the following integration rule:
 * with a for loop
 * with vectorization via slicing
Check the computational time in the two cases.

use the function: $f(x) = 1+2x$ in the range $[1,10]$ as test function.

\begin{equation}
\int_a^b f(x) dx = \frac h 2 f(a) + \frac h 2 f(b) + h \sum_{i=1}^{n-1}f(a+ih)
\end{equation}
where $h = (b-a)/n$